# Generated by Django 3.2.15 on 2022-08-15 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedpost', '0002_auto_20220815_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fiends',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='feedpost.guestprofile'),
        ),
    ]
