# Generated by Django 3.2.13 on 2022-07-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpost', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='child_image',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='id_child',
            field=models.IntegerField(default=None),
        ),
    ]
