# Generated by Django 3.2.15 on 2022-08-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpost', '0006_auto_20220815_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
