# Generated by Django 3.2.15 on 2022-08-19 14:14

from django.db import migrations, models
import feedpost.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpost', '0007_auto_20220816_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='deleted_on',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='edited_on',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='name', max_length=200, verbose_name=feedpost.models.CustomUser),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
